//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogUserProfile
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Bio { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
